services:
  eventhubs-emulator:
    container_name: eventhubs-emulator
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - ./eventhubs-emulator/Config.json:/Eventhubs_Emulator/ConfigFiles/Config.json:ro
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: "Y"
    depends_on:
      - azurite

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  schema-registry:
    container_name: schema-registry
    image: apicurio/apicurio-registry-mem:2.6.2.Final
    ports:
      - "8181:8080"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    pull_policy: always
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: eventhubs-emulator
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: eventhubs-emulator:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="Endpoint=sb://eventhubs-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
    depends_on:
      - eventhubs-emulator

  api:
    container_name: workshop-api
    build:
      context: .
      dockerfile: Nlb.Workshop.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__ReadModel: Data Source=/data/nlb-workshop.db
      Messaging__Provider: EventHubs
      Messaging__Serialization__DefaultFormat: json
      Messaging__EventHubs__ConnectionString: Endpoint=sb://eventhubs-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      Messaging__EventHubs__EventHubName: orders
      Messaging__EventHubs__ConsumerGroup: projection
      Messaging__EventHubs__ReplayConsumerGroup: replay
      Messaging__EventHubs__CheckpointBlobConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      Messaging__EventHubs__CheckpointContainerName: checkpoints
      Messaging__Kafka__BootstrapServers: eventhubs-emulator:9092
      Messaging__Kafka__Topic: orders
      Messaging__Kafka__ConsumerGroup: projection
      Messaging__Kafka__ReplayConsumerGroup: replay
      Messaging__Kafka__SecurityProtocol: SaslPlaintext
      Messaging__Kafka__SaslMechanism: Plain
      Messaging__Kafka__SaslUsername: $$ConnectionString
      Messaging__Kafka__SaslPassword: Endpoint=sb://eventhubs-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
    volumes:
      - readmodel-data:/data
    depends_on:
      - eventhubs-emulator
      - azurite

  consumer:
    container_name: workshop-consumer
    build:
      context: .
      dockerfile: Nlb.Workshop.Consumer.Worker/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__ReadModel: Data Source=/data/nlb-workshop.db
      Messaging__Provider: EventHubs
      Messaging__Serialization__DefaultFormat: json
      Messaging__EventHubs__ConnectionString: Endpoint=sb://eventhubs-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      Messaging__EventHubs__EventHubName: orders
      Messaging__EventHubs__ConsumerGroup: projection
      Messaging__EventHubs__ReplayConsumerGroup: replay
      Messaging__EventHubs__CheckpointBlobConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      Messaging__EventHubs__CheckpointContainerName: checkpoints
      Messaging__Kafka__BootstrapServers: eventhubs-emulator:9092
      Messaging__Kafka__Topic: orders
      Messaging__Kafka__ConsumerGroup: projection
      Messaging__Kafka__ReplayConsumerGroup: replay
      Messaging__Kafka__SecurityProtocol: SaslPlaintext
      Messaging__Kafka__SaslMechanism: Plain
      Messaging__Kafka__SaslUsername: $$ConnectionString
      Messaging__Kafka__SaslPassword: Endpoint=sb://eventhubs-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
    volumes:
      - readmodel-data:/data
    depends_on:
      - eventhubs-emulator
      - azurite

volumes:
  readmodel-data:
